# Adapted from various sources, including:
# - Louis Dionne's Hana: https://github.com/ldionne/hana
# - Paul Fultz II's FIT: https://github.com/pfultz2/Fit
# - Eric Niebler's range-v3: https://github.com/ericniebler/range-v3
sudo: required
language: cpp

addons: &gcc48
  apt:
    packages:
      - g++-4.8
      - valgrind
    sources:
      - ubuntu-toolchain-r-test

addons: &gcc49
  apt:
    packages:
      - g++-4.9
      - valgrind
    sources:
      - ubuntu-toolchain-r-test

addons: &gcc7
  apt:
    packages:
      - g++-7
      - valgrind
    sources:
      - ubuntu-toolchain-r-test

addons: &clang35
  apt:
    packages:
      - clang-3.5
      - valgrind
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5

addons: &clang6
  apt:
    packages:
      - clang-6.0
      - valgrind
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0

matrix:
  include:
    # Test gcc-4.8: C++11, Build=Debug/Release
    - env: GCC_VERSION=4.8 BUILD_TYPE=Debug CPP=11
      os: linux
      addons: *gcc48

    - env: GCC_VERSION=4.8 BUILD_TYPE=Release CPP=11
      os: linux
      addons: *gcc48

    # Test gcc-4.9: C++11, Build=Debug/Release
    - env: GCC_VERSION=4.9 BUILD_TYPE=Debug CPP=11
      os: linux
      addons: *gcc49

    - env: GCC_VERSION=4.9 BUILD_TYPE=Release CPP=11
      os: linux
      addons: *gcc49

    # Test gcc-7: C++11, Build=Debug/Release
    - env: GCC_VERSION=7 BUILD_TYPE=Debug CPP=11
      os: linux
      addons: *gcc7

    - env: GCC_VERSION=7 BUILD_TYPE=Release CPP=11
      os: linux
      addons: *gcc7

    # Test clang-3.5: C++11, Build=Debug/Release
    - env: CLANG_VERSION=3.5 BUILD_TYPE=Debug CPP=11
      os: linux
      addons: *clang35

    - env: CLANG_VERSION=3.5 BUILD_TYPE=Release CPP=11
      os: linux
      addons: *clang35

      # Test clang-6.0: C++11, Build=Debug, ASAN=On
    - env: CLANG_VERSION=6.0 BUILD_TYPE=Debug CPP=11 ASAN=On
      os: linux
      addons: *clang6

      # Test clang-6.0: C++11, Build=Debug, TSAN=On
    - env: CLANG_VERSION=6.0 BUILD_TYPE=Debug CPP=11 TSAN=On
      os: linux
      addons: *clang6

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
  - which $CXX
  - which $CC
  - which valgrind
  - $CXX --version
  - cmake --version
  - valgrind --version

install:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - |
    cmake .. \
      --warn-uninitialized \
      -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
      -DCMAKE_CXX_STANDARD=$CPP \
      -DSPDLOG_BUILD_EXAMPLES=ON \
      -DSPDLOG_SANITIZE_THREAD=$TSAN \
      -DSPDLOG_SANITIZE_ADDRESS=$ASAN
  - VERBOSE=1 make -j2

script:
  - export TSAN_OPTIONS=verbosity=1
  - if [ "$ASAN" != "On" ] && [ "$TSAN" != "On" ]; then CTEST_FLAGS="-DExperimentalMemCheck"; fi
  - ctest -j2 -VV $CTEST_FLAGS

notifications:
  email: false
